aws:
  db-instance-identifier: dbInstanceIdentifier
  aws-secrets-manager-name: AWS Secrets Manager
  region: us-east-1
  db-name: dbName

logging:
  databus:
    url: splunk-url
  level:
    '[org.springframework.web]': DEBUG
    '[com.sample.awsrds]': DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} | %-5level | %msg%n'

spring:
  datasource:
    url: jdbc:mysql://<ENDPOINT>:3306/example
    username: root
    password: Password
  jpa:
    show-sql: true
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      '[max_allowed_packet]': 2000